export enum Characteristics {
  TimeManagement = "TimeManagement",
  Discipline = "Discipline",
  Consistency = "Consistency",
  Focus = "Focus",
  StressHandling = "StressHandling",
  PlanningAbility = "PlanningAbility",
  MotivationStability = "MotivationStability",
  Accountability = "Accountability",
  WorkEthic = "WorkEthic",
  Adaptability = "Adaptability",
  Prioritization = "Prioritization",
  Efficiency = "Efficiency",
  SelfControl = "SelfControl",
  LearningSpeed = "LearningSpeed",
  Reliability = "Reliability",
  GoalOrientation = "GoalOrientation",
  Resilience = "Resilience",
  AttentionToDetail = "AttentionToDetail",
  Independence = "Independence",
  DecisionMaking = "DecisionMaking",
}
