import type { Metadata } from "next";
import { Noto_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import QuizProvider from "@/contexts/QuizContext";
import GlobalNavbar from "@/components/GlobalNavbar";
import GlobalFooter from "@/components/GlobalFooter";
import { MobileGate } from "@/components/MobileGate";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSans.variable} ${notoSerif.variable} h-full text-gray-900 antialiased`}
    >
      <QuizProvider>
        <body className="flex min-h-screen flex-col">
          <MobileGate>
            <div className="flex min-h-screen flex-1 flex-col">
              <GlobalNavbar />
              <div className="flex flex-1 flex-col justify-center py-16">
                {children}
              </div>
            </div>
            <GlobalFooter />
            <UserNotice />
          </MobileGate>
        </body>
      </QuizProvider>
    </html>
  );
}

function UserNotice() {
  return (
    <div className="fixed bottom-4 left-4 z-50 max-w-xs rounded-md border border-yellow-200 bg-yellow-50 p-4 shadow-md">
      <p className="text-sm font-semibold text-yellow-800">Work in progress</p>
      <p className="mt-1 text-xs text-yellow-700">
        This page is not yet complete and may contain bugs or unstable
        implementations. Do not consider it production-ready.
      </p>
    </div>
  );
}
