import type { Metadata } from "next";
import "./globals.css";
import QuizProvider from "@/contexts/QuizContext";
import AppNavbar from "@/components/AppNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="flex min-h-full flex-col">
        <QuizProvider>
          <AppNavbar />
          {children}
        </QuizProvider>
      </body>
    </html>
  );
}
