import type { Metadata } from "next";
import { Noto_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import QuizProvider from "@/contexts/QuizContext";
import GlobalNavbar from "@/components/GlobalNavbar";
import GlobalFooter from "@/components/GlobalFooter";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSans.variable} ${notoSerif.variable} h-full text-gray-900 antialiased`}
    >
      <QuizProvider>
        <body className="flex min-h-screen flex-col">
          <div className="flex min-h-screen flex-1 flex-col">
            <GlobalNavbar />
            <div className="flex flex-1 flex-col justify-center py-16">
              {children}
            </div>
          </div>
          <GlobalFooter />
        </body>
      </QuizProvider>
    </html>
  );
}
